# Documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "tsa96"
      - "GordiNoki"
    # Stops non-security updates from being created
    open-pull-requests-limit: 0
    # Split prod and dev dependencies into separate groups -- prod is more
    # important, and Nx-dependent dev stuff always requires manual work.
    groups:
      production-security-updates:
        applies-to: security-updates
        dependency-type: "production"
      development-security-updates:
        applies-to: security-updates
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
