version: '3.8'

services:
  db:
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  api:
    image: docker.pkg.github.com/momentum-mod/website/mmod-website:staging
    restart: unless-stopped
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    expose:
      - ${NODE_PORT}
    environment:
      IS_DOCKERIZED_API: 'true'
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?schema=public
    # TODO: This looks like old API pre-S3 shit. Probably remove when setting up prod properly.
    volumes:
      - ./server/public/img/maps:/app/server/public/img/maps
      - ./server/public/maps:/app/server/public/maps
      - ./server/public/runs:/app/server/public/runs
    command: sh -c "npm", "run", "start:migrate:prod"
