services:
  postgres:
    container_name: postgres
    image: postgres:18
    restart: unless-stopped
  valkey:
    image: valkey/valkey:8.1.3
    container_name: valkey
  rustfs:
    image: rustfs/rustfs:1.0.0
    container_name: rustfs
  createbuckets:
    image: rustfs/rc:v0.1.36
    container_name: rustfs_create_buckets
    depends_on:
      rustfs:
        condition: service_healthy
