services:
  postgres:
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 10s
      retries: 3
  valkey:
    restart: unless-stopped
    environment:
      "VALKEY_EXTRA_FLAGS": "--port ${VALKEY_PORT}"
    expose:
      - ${VALKEY_PORT}
    ports:
      - ${VALKEY_PORT}:${VALKEY_PORT}
    healthcheck:
      test: [
        "CMD-SHELL",
        "valkey-cli ping | grep PONG"
      ]
      interval: 5s
      timeout: 10s
      retries: 3
  rustfs:
    restart: unless-stopped
    command: /data
    user: root
    env_file:
      - .env
    environment:
      - RUSTFS_REGION=${STORAGE_REGION}
      - RUSTFS_ADDRESS=:${RUSTFS_SERVER_PORT}
      - RUSTFS_CONSOLE_ADDRESS=:${RUSTFS_CONSOLE_PORT}
      - RUSTFS_CONSOLE_ENABLE=true
    ports:
      - ${RUSTFS_SERVER_PORT}:${RUSTFS_SERVER_PORT}
      - ${RUSTFS_CONSOLE_PORT}:${RUSTFS_CONSOLE_PORT}
    expose:
      - ${RUSTFS_SERVER_PORT}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${RUSTFS_SERVER_PORT}/health']
      interval: 5s
      timeout: 20s
      retries: 3
    volumes:
     - ./data/rustfs:/data
  createbuckets:
    env_file:
      - .env
    entrypoint: >
     sh -c "
       rc alias set momentum http://rustfs:${RUSTFS_SERVER_PORT} ${RUSTFS_ACCESS_KEY} ${RUSTFS_SECRET_KEY} &&
       rc bucket create momentum/${STORAGE_BUCKET_NAME} --ignore-existing &&
       rc bucket anonymous set public momentum/${STORAGE_BUCKET_NAME} &&
       if ! rc bucket lifecycle rule list momentum/${STORAGE_BUCKET_NAME} | grep -q 'upload_tmp/'; then
        rc bucket lifecycle rule add --prefix 'upload_tmp/' --expiry-days 1 momentum/${STORAGE_BUCKET_NAME}
       fi
     "
  pgadmin:
    container_name: pgadmin
    env_file:
      - .env
    image: dpage/pgadmin4
    restart: always
    profiles:
      - pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
