export enum AdminActivityType {
  USER_UPDATE = 0,
  USER_CREATE_PLACEHOLDER = 1,
  USER_MERGE = 2,
  USER_DELETE = 3,
  MAP_UPDATE = 4,
  MAP_CONTENT_DELETE = 5,
  REPORT_UPDATE = 6,
  REPORT_RESOLVE = 7,
  REVIEW_DELETED = 8,
  REVIEW_COMMENT_DELETED = 9
}
