export enum AdminActivityType {
  USER_UPDATE_ROLES = 0,
  USER_UPDATE_BANS = 1,
  USER_UPDATE_ALIAS = 2,
  USER_UPDATE_BIO = 3,
  USER_CREATE_PLACEHOLDER = 4,
  USER_MERGE = 5,
  USER_DELETE = 6,
  MAP_UPDATE = 7,
  MAP_DELETE = 8,
  REPORT_UPDATE = 9,
  REPORT_RESOLVE = 10
}
