// noinspection JSUnusedGlobalSymbols
export {
  mdiAlert,
  mdiFlagOutline,
  mdiCloseCircleOutline,
  mdiMenu,
  // This is better than `map` or similar for symbolising Source engine maps!
  mdiPanoramaOutline,
  mdiEarth,
  mdiTrophy,
  mdiTrophyOutline,
  mdiAccountMultipleOutline,
  mdiGiftOutline,
  mdiBellAlert,
  mdiBellOutline,
  mdiMagnify,
  mdiCheckCircleOutline,
  mdiPlusOutline,
  mdiImageEditOutline,
  mdiFolder,
  mdiFolderOutline,
  mdiStar,
  mdiStarOutline,
  mdiDownloadOutline,
  mdiPlayCircleOutline,
  mdiArrowRightThick,
  mdiTooltipQuestionOutline,
  mdiChevronLeftCircleOutline,
  mdiChevronRightCircleOutline,
  mdiNoteEdit,
  mdiNotebookOutline,
  mdiForumOutline,
  mdiFileOutline,
  mdiChartPieOutline,
  mdiImageEdit
} from '@mdi/js';
