name: 🐛 Bug Report
description: Create a bug report to help us improve the site.
labels: ["Type: Bug"]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is. If applicable, include screenshots to help explain.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Operating system and browser
    description: Provide the operating system and the browser it occured on.
    placeholder: |
      - OS: iOS
      - Browser: Chrome, Safari
      - Version: 22
  validations:
    required: true
- type: textarea
  attributes:
    label: Website information
    description: The version/Git commit of the website
    placeholder: Version 0.1.0
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the bug here.
  validations:
    required: false
