name: ❓ I Have a Question
description: Do you need help? This is the way to get it!
labels: ["Type: Question"]
body:
- type: textarea
  attributes:
    label: The question
    description: A clear and concise question you have.
    placeholder: I'm confused about...
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the question here.
  validations:
    required: false
