name: ♻️ Refactor
description: Something that needs improving while not changing functionality.
labels: ["Type: Enhancement"]
body:
- type: textarea
  attributes:
    label: Describe the change
    description: A clear and concise description of what needs changed. If applicable, include screenshots to help explain.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the change here.
  validations:
    required: false
