name: 👷 DevOps & CI/CD
description: An issue relating to updating the pipline
labels: ["For: DevOps"]
body:
- type: textarea
  attributes:
    label: Describe the issue
    description: A clear and concise description of what needs updating.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the issue here.
  validations:
    required: false
