export const MAX_DAILY_REPORTS = 5;
export const MAX_MAP_IMAGE_UPLOADS = 5;
export const MAX_PENDING_MAPS = 3;
export const MAX_BSP_SIZE = 300_000_000;
export const MAX_VMF_SIZE = 100_000_000;
export const MAX_MAP_IMAGE_SIZE = 5_000_000;
export const MAX_IMAGE_SIZE = 1e7;
export const MAX_CREDIT_DESCRIPTION_LENGTH = 64;
export const MAX_REVIEW_LENGTH = 50_000;
export const MAX_TESTING_REQUESTS = 20;
export const MIN_PUBLIC_TESTING_DURATION = 7 * 24 * 60 * 60 * 1000;
export const MAX_CREDITS_EXCEPT_TESTERS = 20;
export const MAX_BIO_LENGTH = 2000;
export const MAX_MAP_DESCRIPTION_LENGTH = 1500;
export const MIN_MAP_NAME_LENGTH = 3;
export const MAX_MAP_NAME_LENGTH = 64; // Seems high but this is actually a constant in engine.
export const MAX_MAP_SUGGESTION_COMMENT_LENGTH = 500;
