export const MAX_DAILY_REPORTS = 5;
export const MAX_MAP_IMAGES = 5;
export const MAX_BSP_SIZE = 300_000_000;
export const MAX_VMF_SIZE = 100_000_000;
export const MAX_MAP_IMAGE_SIZE = 10_000_000;
export const MAP_IMAGE_WIDTH = 2560;
export const MAP_IMAGE_HEIGHT = 1440;
export const MAX_CREDIT_DESCRIPTION_LENGTH = 64;
export const MAX_CHANGELOG_LENGTH = 1500;
export const MAX_REVIEW_LENGTH = 5000;
export const MAX_REVIEW_IMAGES = 20;
export const MAX_REVIEW_COMMENT_LENGTH = 1000;
export const MAX_TEST_INVITES = 20;
export const MIN_PUBLIC_TESTING_DURATION = 7 * 24 * 60 * 60 * 1000;
export const MAX_CREDITS_EXCEPT_TESTERS = 20;
export const MAX_USER_ALIAS_LENGTH = 32; // Based on Steam username limit.
export const MAX_BIO_LENGTH = 2000;
export const MIN_MAP_DESCRIPTION_LENGTH = 10;
export const MAX_MAP_DESCRIPTION_LENGTH = 1500;
export const MIN_MAP_NAME_LENGTH = 3;
export const MAX_MAP_NAME_LENGTH = 32; // Seems high but this is actually a constant in engine.
export const MAX_OPEN_MAP_SUBMISSIONS = 20;
export const MAX_MAPPER_OPEN_MAP_SUBMISSIONS = 100;
export const MAX_MAP_SUGGESTION_COMMENT_LENGTH = 500;
export const PRE_SIGNED_URL_EXPIRE_TIME = 5 * 60;
export const MAX_ADMIN_ANNOUNCEMENT_LENGTH = 500;
