name: Publish Staging Frontend

on:
  push:
    branches:
      - main
    paths-ignore:
      - "apps/backend*/**"

jobs:
  publish_frontend:
    uses: momentum-mod/website/.github/workflows/frontend_cf_pages.yml@main
    with:
      project_name: 'frontend-staging'
    secrets: inherit
