name: Tests

on:
  pull_request:
    branches:
      - staging
    paths-ignore:
      - '**.md'
  push:
    branches:
      - staging
    paths-ignore:
      - '**.md'
      
env:
  NODE_ENV: test

jobs:
  client-tests:
    name: Client Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Resolve Yarn Cache Directory
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache Yarn Cache Directory
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('./client/yarn.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-

    - name: Run Tests
      run: |
        cd ./client/
        npm install -g @angular/cli && yarn install --prefer-offline
        npm run test
  
  server-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Execute tests
      run: docker compose -f docker-compose.yml -f docker-compose.test.yml up -d
